#!/bin/bash
cd data
for FILE in *; do
gnuplot <<- EOF
	set xlabel "x"
	set ylabel "y"
	set term png
	set output "${FILE}.png"
        #set xrange [0:1]
        #set yrange [0:1]
	plot "${FILE}" using 1:2:3 with image title "Density"
	EOF
done
convert -delay 5 -loop 0 *.png density.gif
cd ..
